// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpEnp8sPu1bXRy-D5PS-WXEFYlSOrGv7I',
    appId: '1:515733548489:web:87242d757371402b980c18',
    messagingSenderId: '515733548489',
    projectId: 'education-app-a7dd5',
    authDomain: 'education-app-a7dd5.firebaseapp.com',
    storageBucket: 'education-app-a7dd5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzJo26-Hk-YPV6A0jQZp2VemTaKM4SBCQ',
    appId: '1:515733548489:android:a2c900ae20aa49f1980c18',
    messagingSenderId: '515733548489',
    projectId: 'education-app-a7dd5',
    storageBucket: 'education-app-a7dd5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL6FThDUwyLqA8zJSz02NGNGrMQrBi_q8',
    appId: '1:515733548489:ios:43810841c9fc8c8b980c18',
    messagingSenderId: '515733548489',
    projectId: 'education-app-a7dd5',
    storageBucket: 'education-app-a7dd5.appspot.com',
    iosBundleId: 'com.dbestech.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL6FThDUwyLqA8zJSz02NGNGrMQrBi_q8',
    appId: '1:515733548489:ios:4b7ae8e57735163b980c18',
    messagingSenderId: '515733548489',
    projectId: 'education-app-a7dd5',
    storageBucket: 'education-app-a7dd5.appspot.com',
    iosBundleId: 'com.dbestech.educationApp.RunnerTests',
  );
}
